#!/usr/bin/env python3
"""Generate firmware/stm32/include/robogame_protocol.h from the Python
protocol table (core/protocol/messages.py).

Python and C share one source of truth — SOF, VERSION, MSG_IDs, payload
layouts are guaranteed consistent. Regenerate after any protocol change:

    python3 scripts/gen_protocol_header.py
"""
from __future__ import annotations

import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO))

from core.protocol import MESSAGES, SOF1, SOF2, VERSION  # noqa: E402

HEADER = REPO / "firmware" / "stm32" / "include" / "robogame_protocol.h"

TEMPLATE = """\
/* robogame_protocol.h — Pi <-> STM32 binary protocol definitions.
 *
 * AUTO-GENERATED by scripts/gen_protocol_header.py — DO NOT EDIT BY HAND.
 * Source of truth: core/protocol/messages.py
 *
 * Frame layout (little endian, packed):
 *   SOF(0xAA 0x55) VERSION SEQ MSG_ID LEN(u16) PAYLOAD CRC16(u16)
 * CRC16-CCITT (poly 0x1021, init 0xFFFF) over VERSION..PAYLOAD.
 */

#ifndef ROBOGAME_PROTOCOL_H
#define ROBOGAME_PROTOCOL_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {{
#endif

/* ---- frame constants (must match core.protocol.messages) ---- */
#define RG_SOF1            {sof1:#04x}u
#define RG_SOF2            {sof2:#04x}u
#define RG_VERSION         {version:#04x}u
#define RG_HEADER_SIZE     7u
#define RG_CRC_SIZE        2u
#define RG_MAX_PAYLOAD     {max_payload}u

/* message ids */
typedef enum {{
{msg_id_enum}
}} rg_msg_id_t;

/* direction of each message */
{direction_defines}

/* ---- payload structs (packed) ---- */
{payload_structs}

/* CRC16-CCITT (poly 0x1021, init 0xFFFF, no reflection) */
uint16_t rg_crc16(const uint8_t *data, uint32_t len);

#ifdef __cplusplus
}}
#endif

#endif /* ROBOGAME_PROTOCOL_H */
"""


def c_name(name: str) -> str:
    return "rg_" + name.lower()


def main() -> int:
    check_only = "--check" in sys.argv
    specs = sorted(MESSAGES.values(), key=lambda s: s.msg_id)

    id_lines = []
    for s in specs:
        id_lines.append(f"    RG_{s.name} = {s.msg_id:#04x},  /* {s.direction} */")
    # tidy: remove trailing comma on last entry
    id_lines[-1] = id_lines[-1].rstrip(",")
    msg_id_enum = "\n".join(id_lines)

    dir_lines = []
    for s in specs:
        d = "PI_TO_MCU" if s.direction == "pi_to_mcu" else "MCU_TO_PI"
        dir_lines.append(f"#define RG_DIR_{s.name:<24} RG_{d}")
    direction_defines = "\n".join(dir_lines)

    structs = []
    for s in specs:
        fields = []
        for f in s.fields:
            cmt = f" /* {f.comment} */" if f.comment else ""
            fields.append(f"    {f.c_type} {f.name};{cmt}")
        body = "\n".join(fields) if fields else "    uint8_t _dummy;"
        structs.append(
            f"/* {s.direction}: payload {s.payload_size} bytes */\n"
            f"typedef struct __attribute__((packed)) {{\n{body}\n}} {c_name(s.name)}_t;"
        )
    payload_structs = "\n\n".join(structs)

    content = TEMPLATE.format(
        sof1=SOF1, sof2=SOF2, version=VERSION,
        max_payload=256,
        msg_id_enum=msg_id_enum,
        direction_defines=direction_defines,
        payload_structs=payload_structs,
    )

    if check_only:
        current = (HEADER.read_text(encoding="utf-8")
                   if HEADER.exists() else "")
        if current != content:
            print(f"ERROR: {HEADER} is out of date with "
                  "core/protocol/messages.py — regenerate with:\n"
                  "    python scripts/gen_protocol_header.py")
            return 1
        print(f"{HEADER} up to date ({len(specs)} messages)")
        return 0

    HEADER.parent.mkdir(parents=True, exist_ok=True)
    HEADER.write_text(content, encoding="utf-8")
    print(f"generated {HEADER} ({len(specs)} messages)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
