/* robogame_protocol.h — Pi <-> STM32 binary protocol definitions.
 *
 * AUTO-GENERATED by scripts/gen_protocol_header.py — DO NOT EDIT BY HAND.
 * Source of truth: core/protocol/messages.py
 *
 * Frame layout (little endian, packed):
 *   SOF(0xAA 0x55) VERSION SEQ MSG_ID LEN(u16) PAYLOAD CRC16(u16)
 * CRC16-CCITT (poly 0x1021, init 0xFFFF) over VERSION..PAYLOAD.
 */

#ifndef ROBOGAME_PROTOCOL_H
#define ROBOGAME_PROTOCOL_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ---- frame constants (must match core.protocol.messages) ---- */
#define RG_SOF1            0xaau
#define RG_SOF2            0x55u
#define RG_VERSION         0x01u
#define RG_HEADER_SIZE     7u
#define RG_CRC_SIZE        2u
#define RG_MAX_PAYLOAD     256u

/* message ids */
typedef enum {
    RG_HEARTBEAT = 0x01,  /* pi_to_mcu */
    RG_CMD_STOP = 0x02,  /* pi_to_mcu */
    RG_CMD_VELOCITY = 0x03,  /* pi_to_mcu */
    RG_CMD_LINE_FOLLOW_START = 0x04,  /* pi_to_mcu */
    RG_CMD_LINE_FOLLOW_STOP = 0x05,  /* pi_to_mcu */
    RG_CMD_LINE_FOLLOW_CONFIG = 0x06,  /* pi_to_mcu */
    RG_CMD_LINEAR_AXIS = 0x07,  /* pi_to_mcu */
    RG_CMD_GRIPPER = 0x08,  /* pi_to_mcu */
    RG_CMD_HOME = 0x09,  /* pi_to_mcu */
    RG_MCU_HEARTBEAT = 0x81,  /* mcu_to_pi */
    RG_ODOMETRY = 0x82,  /* mcu_to_pi */
    RG_IMU = 0x83,  /* mcu_to_pi */
    RG_LINE_STATE = 0x84,  /* mcu_to_pi */
    RG_MANIPULATOR_STATE = 0x85,  /* mcu_to_pi */
    RG_LIMIT_STATE = 0x86,  /* mcu_to_pi */
    RG_FAULT = 0x87,  /* mcu_to_pi */
    RG_START_EVENT = 0x88,  /* mcu_to_pi */
} rg_msg_id_t;

/* direction of each message */
#define RG_DIR_HEARTBEAT                RG_PI_TO_MCU
#define RG_DIR_CMD_STOP                 RG_PI_TO_MCU
#define RG_DIR_CMD_VELOCITY             RG_PI_TO_MCU
#define RG_DIR_CMD_LINE_FOLLOW_START    RG_PI_TO_MCU
#define RG_DIR_CMD_LINE_FOLLOW_STOP     RG_PI_TO_MCU
#define RG_DIR_CMD_LINE_FOLLOW_CONFIG   RG_PI_TO_MCU
#define RG_DIR_CMD_LINEAR_AXIS          RG_PI_TO_MCU
#define RG_DIR_CMD_GRIPPER              RG_PI_TO_MCU
#define RG_DIR_CMD_HOME                 RG_PI_TO_MCU
#define RG_DIR_MCU_HEARTBEAT            RG_MCU_TO_PI
#define RG_DIR_ODOMETRY                 RG_MCU_TO_PI
#define RG_DIR_IMU                      RG_MCU_TO_PI
#define RG_DIR_LINE_STATE               RG_MCU_TO_PI
#define RG_DIR_MANIPULATOR_STATE        RG_MCU_TO_PI
#define RG_DIR_LIMIT_STATE              RG_MCU_TO_PI
#define RG_DIR_FAULT                    RG_MCU_TO_PI
#define RG_DIR_START_EVENT              RG_MCU_TO_PI

/* ---- payload structs (packed) ---- */
/* pi_to_mcu: payload 4 bytes */
typedef struct __attribute__((packed)) {
    uint32_t uptime_ms; /* Pi uptime in ms */
} rg_heartbeat_t;

/* pi_to_mcu: payload 1 bytes */
typedef struct __attribute__((packed)) {
    uint8_t mode; /* 0=soft stop, 1=brake */
} rg_cmd_stop_t;

/* pi_to_mcu: payload 12 bytes */
typedef struct __attribute__((packed)) {
    float vx; /* body forward velocity m/s */
    float vy; /* body lateral velocity m/s */
    float wz; /* yaw rate rad/s */
} rg_cmd_velocity_t;

/* pi_to_mcu: payload 6 bytes */
typedef struct __attribute__((packed)) {
    uint16_t segment_id; /* route segment identifier */
    float target_speed; /* m/s */
} rg_cmd_line_follow_start_t;

/* pi_to_mcu: payload 0 bytes */
typedef struct __attribute__((packed)) {
    uint8_t _dummy;
} rg_cmd_line_follow_stop_t;

/* pi_to_mcu: payload 12 bytes */
typedef struct __attribute__((packed)) {
    float kp;
    float ki;
    float kd;
} rg_cmd_line_follow_config_t;

/* pi_to_mcu: payload 9 bytes */
typedef struct __attribute__((packed)) {
    uint8_t axis; /* 0=X, 1=Z */
    float position_mm; /* target position */
    float speed; /* mm/s, 0=default */
} rg_cmd_linear_axis_t;

/* pi_to_mcu: payload 1 bytes */
typedef struct __attribute__((packed)) {
    uint8_t command; /* 0=open, 1=close */
} rg_cmd_gripper_t;

/* pi_to_mcu: payload 1 bytes */
typedef struct __attribute__((packed)) {
    uint8_t axis; /* 0=X, 1=Z, 0xFF=all */
} rg_cmd_home_t;

/* mcu_to_pi: payload 8 bytes */
typedef struct __attribute__((packed)) {
    uint32_t uptime_ms;
    uint32_t fault_flags; /* bitmask */
} rg_mcu_heartbeat_t;

/* mcu_to_pi: payload 24 bytes */
typedef struct __attribute__((packed)) {
    float x; /* map frame, m */
    float y;
    float yaw; /* rad */
    float vx; /* body frame, m/s */
    float vy;
    float wz; /* rad/s */
} rg_odometry_t;

/* mcu_to_pi: payload 16 bytes */
typedef struct __attribute__((packed)) {
    float yaw; /* integrated heading rad */
    float gyro_z; /* rad/s */
    float accel_x; /* m/s^2 */
    float accel_y; /* m/s^2 */
} rg_imu_t;

/* mcu_to_pi: payload 12 bytes */
typedef struct __attribute__((packed)) {
    uint8_t line_detected;
    float line_error; /* normalized lateral error */
    float confidence; /* 0..1 */
    uint8_t controller_state; /* 0=idle 1=running 2=lost 3=fault */
    uint8_t intersection_detected;
    uint8_t fault;
} rg_line_state_t;

/* mcu_to_pi: payload 17 bytes */
typedef struct __attribute__((packed)) {
    float x_mm;
    float z_mm;
    uint8_t homed;
    uint8_t gripper_state; /* 0=unknown 1=open 2=closed 3=holding 4=fault */
    uint8_t grip_detected;
    uint8_t moving;
    uint8_t fault;
    uint32_t fault_code;
} rg_manipulator_state_t;

/* mcu_to_pi: payload 4 bytes */
typedef struct __attribute__((packed)) {
    uint32_t bitmask; /* limit switch bitmap */
} rg_limit_state_t;

/* mcu_to_pi: payload 8 bytes */
typedef struct __attribute__((packed)) {
    uint32_t fault_code;
    uint32_t detail;
} rg_fault_t;

/* mcu_to_pi: payload 1 bytes */
typedef struct __attribute__((packed)) {
    uint8_t button_state; /* 1=pressed */
} rg_start_event_t;

/* CRC16-CCITT (poly 0x1021, init 0xFFFF, no reflection) */
uint16_t rg_crc16(const uint8_t *data, uint32_t len);

#ifdef __cplusplus
}
#endif

#endif /* ROBOGAME_PROTOCOL_H */
