/* robogame_protocol.h — Pi <-> STM32 binary protocol definitions (v1.1).
 *
 * AUTO-GENERATED by scripts/gen_protocol_header.py — DO NOT EDIT BY HAND.
 * Source of truth: core/protocol/messages.py
 * Spec: docs/downward/robohead_transmission_protocol.md
 *
 * Frame layout (little endian, packed):
 *   SOF(0xAA 0x55) VER MSG_ID SEQ LEN(u8) PAYLOAD CRC16(u16, LE)
 * CRC-16/CCITT-FALSE (poly 0x1021, init 0xFFFF, no reflection, xorout 0)
 * over VER..PAYLOAD (SOF excluded, CRC itself excluded).
 */

#ifndef ROBOGAME_PROTOCOL_H
#define ROBOGAME_PROTOCOL_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ---- frame constants (must match core.protocol.messages) ---- */
#define RG_SOF1            0xaau
#define RG_SOF2            0x55u
#define RG_VERSION         0x01u
#define RG_HEADER_SIZE     6u
#define RG_CRC_SIZE        2u
#define RG_MAX_PAYLOAD     255u

/* message ids */
typedef enum {
    RG_CMD_VEL = 0x01,  /* pi_to_mcu */
    RG_CMD_ACTION = 0x02,  /* pi_to_mcu */
    RG_ODOM = 0x81,  /* mcu_to_pi */
    RG_LINE_SENSOR = 0x82,  /* mcu_to_pi */
    RG_ROBOT_STATE = 0x83,  /* mcu_to_pi */
} rg_msg_id_t;

/* direction of each message */
#define RG_DIR_CMD_VEL                  RG_PI_TO_MCU
#define RG_DIR_CMD_ACTION               RG_PI_TO_MCU
#define RG_DIR_ODOM                     RG_MCU_TO_PI
#define RG_DIR_LINE_SENSOR              RG_MCU_TO_PI
#define RG_DIR_ROBOT_STATE              RG_MCU_TO_PI

/* ---- CMD_ACTION action_id (protocol §5.2) ---- */
#define RG_ACTION_GRIPPER_OPEN  0x01
#define RG_ACTION_GRIPPER_CLOSE 0x02
#define RG_ACTION_LIFT_UP       0x03
#define RG_ACTION_LIFT_DOWN     0x04
#define RG_ACTION_STOP_ALL      0x05

/* ---- ROBOT_STATE enums (protocol §6.3) ---- */
#define RG_MOTOR_DISABLED 0x00
#define RG_MOTOR_IDLE     0x01
#define RG_MOTOR_RUNNING  0x02
#define RG_MOTOR_TIMEOUT  0x03
#define RG_MOTOR_FAULT    0x04

#define RG_GRIPPER_UNKNOWN 0x00
#define RG_GRIPPER_OPENED  0x01
#define RG_GRIPPER_CLOSED  0x02
#define RG_GRIPPER_HOLDING 0x03
#define RG_GRIPPER_FAULT   0x04

#define RG_LIFT_UNKNOWN     0x00
#define RG_LIFT_IDLE        0x01
#define RG_LIFT_MOVING_UP   0x02
#define RG_LIFT_MOVING_DOWN 0x03
#define RG_LIFT_FAULT       0x04

#define RG_ERR_CHASSIS      0x01
#define RG_ERR_GRIPPER      0x02
#define RG_ERR_LIFT         0x04
#define RG_ERR_COMM_TIMEOUT 0x08
#define RG_ERR_LOW_BATTERY  0x10

/* ---- payload structs (packed) ---- */
/* pi_to_mcu: payload 6 bytes */
typedef struct __attribute__((packed)) {
    int16_t vx_mm_s; /* body forward velocity mm/s */
    int16_t vy_mm_s; /* body lateral velocity mm/s (left +) */
    int16_t wz_mrad_s; /* yaw rate mrad/s (ccw +) */
} rg_cmd_vel_t;

/* pi_to_mcu: payload 3 bytes */
typedef struct __attribute__((packed)) {
    uint8_t action_id; /* ACTION_* constant */
    int16_t param; /* action parameter (see protocol doc) */
} rg_cmd_action_t;

/* mcu_to_pi: payload 18 bytes */
typedef struct __attribute__((packed)) {
    int32_t x_mm; /* accumulated position, world frame */
    int32_t y_mm;
    int32_t theta_mrad; /* continuous heading, never wrapped */
    int16_t vx_mm_s; /* actual body velocity */
    int16_t vy_mm_s;
    int16_t wz_mrad_s;
} rg_odom_t;

/* mcu_to_pi: payload 4 bytes */
typedef struct __attribute__((packed)) {
    uint8_t line_detected; /* 0=lost, 1=detected */
    int16_t offset_mm; /* lateral offset, right of travel dir + */
    uint8_t confidence; /* 0..100 */
} rg_line_sensor_t;

/* mcu_to_pi: payload 4 bytes */
typedef struct __attribute__((packed)) {
    uint8_t motor_state; /* MOTOR_* constant */
    uint8_t gripper_state; /* GRIPPER_* constant */
    uint8_t lift_state; /* LIFT_* constant */
    uint8_t error_code; /* ERR_* bitmask */
} rg_robot_state_t;

/* CRC16-CCITT-FALSE (poly 0x1021, init 0xFFFF, no reflection) */
uint16_t rg_crc16(const uint8_t *data, uint32_t len);

#ifdef __cplusplus
}
#endif

#endif /* ROBOGAME_PROTOCOL_H */
